# Site settings
title: Everton Lima
description: Everton Lima Desenvolvedor Front End
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "http://evertondelima.com.br"

# User settings
username: Everton Lima
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Full Stack Developer
email: ever-tonlima@hotmail.com
linkedin_username: evertonl1ma
github_username:  evertonl1ma
codepen_username:  evertonl1ma

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
